name: Test-Composite-Action
on: 
  workflow_dispatch:

jobs:

  hello_world_job:
  
    runs-on: ubuntu-latest
    
    name: A job to say hello
    steps:
    
      - uses: actions/checkout@v3
      
      - run: ls -l
        shell: bash
        
      - id: foo
        uses: ./actions/hello-world-composite-action
        with:
          who-to-greet: 'Mona the Octocat'
          
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
